name: advent_of_code
description: Advent of Code
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  dijkstra: ^0.0.3
  tuple: ^2.0.1

dev_dependencies:
  lints: ^2.0.0