name: advent_2022
description: advent 2022
version: 1.0.0

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0

flutter:
  uses-material-design: true